service: sls-third-plugin-x-ray # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello

custom:
  trace: true

plugins:
  - serverless-x-ray
